name: WildlandsEssential
main: de.blockorca.wildlandsEssential.Main
version: 1.0
api-version: 1.21
author: Daividyx(BlockOrca)
description: A custom, essentials-like and survival friendly plugin for Spigot servers.
commands:
  menu:
    description: Opens the Plugin's main menu
    usage: /menu
  economy:
    description: Opens the economy menu
    usage: /economy
  warps:
    description: Opens the warp menu
    usage: /warps
  deadchest:
    description: Opens the dead chest menu
    usage: /deadchest
  buyable:
    description: Opens the buyable functions menu
    usage: /buyable
